### ISSUE TITLE
Is this Qiskit Ignis version is right in bug report.md? 

### ISSUE THREAD

**Issue by divshacker** [Qiskit/qiskit-ode#7]
### Informations

- **Qiskit Ignis version**: NA
- **Python version**:NA
- **Operating system**:NA

### What is the current behavior?
`- **Qiskit Ignis version**:`? Is this right or it should be `Qiskit ODE version` or `Qiskit terra version`

**Comment by divshacker** [comment]
Hey @mtreinish may you please have a look ?

**Comment by mtreinish** [comment]
Yeah, this is just a copy and paste error from when I first setup the repo. The template should probably be updated to ask the qiskit-ode version instead of ignis

**Comment by divshacker** [comment]
Done !
